- name: install MySQL (only)
  hosts: debian
  connection: local
  vars:
    MySQL_root_pass: foobar
  tasks:

    - name: Set MySQL root password before installing
      debconf: name='mysql-server' question='mysql-server/root_password' value='{{MySQL_root_pass | quote}}' vtype='password'
      become: yes

    - name: Confirm MySQL root password before installing
      debconf: name='mysql-server' question='mysql-server/root_password_again' value='{{MySQL_root_pass | quote}}' vtype='password'
      become: yes

    - name: Install MySQL packages.
      apt: name="{{item}}" state=present
      become: yes
      with_items:
         - default-mysql-server
         - default-mysql-client