- name: Test Environment
  hosts: proxmox
  tasks:
    - set_fact:
        Win_Srv1: "Windows-ADDC-1" # The target 1 VM name
        Win_Srv2: "Windows-ADDC-2" # The target 2 VM name
        Win_10_1: "Windows-Client-1" # The target 3 VM name
        Win_10_2: "Windows-Client-2" # The target 4 VM name
        Win_10_3: "Windows-Client-3" # The target 5 VM name
        CloneWin_Srv1: "windowsservertemplate" # The 1 VM source
        CloneWin_Srv2: "windowsservertemplate2" # The 2 VM source
        CloneWin_10_1: "windowstemplate" # The 3 VM source
        CloneWin_10_2: "windowstemplate2" # The 4 VM source
        CloneWin_10_3: "windowstemplate3" # The 5 VM source
        apipass: "*" # The Password Used For Signing In To Proxmox
        apihost: "100.124.109.92" # The Proxmox Host IP Address
        apiuser: "root@pam" # The Proxmox User With Access
        prox_storage: "vms-ssd" # The Target Storage On Proxmox
        prox_node: "main" # The Target Node In The Proxmox Cluster
        disk_format: "qcow2" # The Format For The Disk .img
        timeout: "500" # The Task Can Take a While. Adapt
        pause: "10" # How long The Pause Between Tasks Is (Recommend to adjust high if your server is not so strong)
        state: "started" # The State The VM Will Be Put Into After Cloning (Can also be present if you don't want more then one, can also be skipped if none is needed)
    - proxmox_kvm:
        api_user    : "{{ apiuser }}"
        api_password: "{{ apipass }}"
        api_host    : "{{ apihost }}"
        clone       : "{{ CloneWin_Srv1 }}"   
        name        : "{{ Win_Srv1 }}"  
        node        : "{{ prox_node }}"
        storage     : "{{ prox_storage }}"
        format      : "{{ disk_format }}"
        timeout     : "{{ timeout }}"  
    - name: Pause for "{{ pause }}" seconds to clone the "{{ Win_Srv1 }}"
      ansible.builtin.pause:
        seconds: "{{ pause }}"
    - proxmox_kvm:
        api_user    : "{{ apiuser }}"
        api_password: "{{ apipass }}"
        api_host    : "{{ apihost }}"
        clone       : "{{ CloneWin_Srv2 }}"   
        name        : "{{ Win_Srv2 }}"  
        node        : "{{ prox_node }}"
        storage     : "{{ prox_storage }}"
        format      : "{{ disk_format }}"
        timeout     : "{{ timeout }}"  
    - name: Pause for "{{ pause }}" seconds to clone the "{{ Win_Srv2 }}"
      ansible.builtin.pause:
        seconds: "{{ pause }}"
    - proxmox_kvm:
        api_user    : "{{ apiuser }}"
        api_password: "{{ apipass }}"
        api_host    : "{{ apihost }}"
        clone       : "{{ CloneWin_10_1 }}"  
        name        : "{{ Win_10_1 }}"  
        node        : "{{ prox_node }}"
        storage     : "{{ prox_storage }}"
        format      : "{{ disk_format }}"
        timeout     : "{{ timeout }}"  
    - name: Pause for "{{ pause }}" seconds to clone the "{{ Win-10-1 }}"
      ansible.builtin.pause:
        seconds: "{{ pause }}"
    - proxmox_kvm:
        api_user    : "{{ apiuser }}"
        api_password: "{{ apipass }}"
        api_host    : "{{ apihost }}"
        clone       : "{{ CloneWin_10_2 }}"   
        name        : "{{ Win_10_2 }}"  
        node        : "{{ prox_node }}"
        storage     : "{{ prox_storage }}"
        format      : "{{ disk_format }}"
        timeout     : "{{ timeout }}"  
    - name: Pause for "{{ pause }}" seconds to clone the "{{ Win_10_2 }}"
      ansible.builtin.pause:
        seconds: "{{ pause }}"
    - proxmox_kvm:
        api_user    : "{{ apiuser }}"
        api_password: "{{ apipass }}"
        api_host    : "{{ apihost }}"
        clone       : "{{ CloneWin_10_3 }}"   
        name        : "{{ Win_10_3 }}"  
        node        : "{{ prox_node }}"
        storage     : "{{ prox_storage }}"
        format      : "{{ disk_format }}"
        timeout     : "{{ timeout }}" 
    - name: Pause for "{{ pause }}" seconds to clone the "{{ Win_10_3 }}"
      ansible.builtin.pause:
        seconds: "{{ pause }}"
    - name: start "{{ Win_Srv1 }}"
      proxmox_kvm:
        api_user: "{{ apiuser }}"
        api_password: "{{ apipass }}"
        api_host: "{{ apihost }}"
        name: "{{ Win_Srv1 }}"
        node: "{{ prox_node }}"
        state: "{{ state }}"
    - name: Pause for "{{ pause }}" seconds to start the "{{ Win_Srv1 }}"
      ansible.builtin.pause:
        seconds: "{{ pause }}"
    - name: start "{{ Win_Srv2 }}"
      proxmox_kvm:
        api_user: "{{ apiuser }}"
        api_password: "{{ apipass }}"
        api_host: "{{ apihost }}"
        name: "{{ Win_Srv2 }}"
        node: "{{ prox_node }}"
        state: "{{ state }}"
    - name: Pause for "{{ pause }}" seconds to start the "{{ Win_Srv2 }}"
      ansible.builtin.pause:
        seconds: "{{ pause }}"
    - name: start "{{ Win_10_1 }}"
      proxmox_kvm:
        api_user: "{{ apiuser }}"
        api_password: "{{ apipass }}"
        api_host: "{{ apihost }}"
        name: "{{ Win_10_1 }}"
        node: "{{ prox_node }}"
        state: "{{ state }}"
    - name: Pause for "{{ pause }}" seconds to start the "{{ Win_10_1 }}"
      ansible.builtin.pause:
        seconds: "{{ pause }}"
    - name: start "{{ Win_10_2 }}"
      proxmox_kvm:
        api_user: "{{ apiuser }}"
        api_password: "{{ apipass }}"
        api_host: "{{ apihost }}"
        name: "{{ Win_10_2 }}"
        node: "{{ prox_node }}"
        state: "{{ state }}"
    - name: Pause for "{{ pause }}" seconds to start the "{{ Win_10_2 }}"
      ansible.builtin.pause:
        seconds: "{{ pause }}"        
    - name: start "{{ Win_10_3 }}"
      proxmox_kvm:
        api_user: "{{ apiuser }}"
        api_password: "{{ apipass }}"
        api_host: "{{ apihost }}"
        name: "{{ Win_10_3 }}"
        node: "{{ prox_node }}"
        state: "{{ state }}"
    