---
# Variables that an end user should likely never modify.

debian_family_distros:
  - Ubuntu
  - Debian
  - Pop!_OS

centos_family_distros:
  - CentOS
  - Amazon
  - OracleLinux
  - RedHat
  - Rocky
  - AlmaLinux

tailscale_package: tailscale
tailscale_service: tailscaled

repo_description: Tailscale repository

apt_dependencies:
  - gnupg2
  - gnupg-agent
  - apt-transport-https
  - python3-apt

legacy_apt_dependencies:
  # Only install on legacy Debian systems
  - python-apt

debian_distro:
  pop!_os: ubuntu
  ubuntu: ubuntu
  debian: debian

apt_keyring_path: /usr/share/keyrings/tailscale-archive-keyring.gpg

apt_deb: deb [signed-by={{ apt_keyring_path }}] https://pkgs.tailscale.com/{{ release_stability | lower }}/{{ debian_distro[ansible_distribution | lower] }} {{ ansible_distribution_release | lower }} main

apt_signkey: https://pkgs.tailscale.com/{{ release_stability | lower }}/{{ debian_distro[ansible_distribution | lower] }}/{{ ansible_distribution_release | lower }}.noarmor.gpg

yum_dependencies:
  - yum-utils
  - gnupg2

yum_repos:
  Amazon: https://pkgs.tailscale.com/{{ release_stability | lower }}/amazon-linux/{{ ansible_distribution_major_version }}/tailscale.repo
  CentOS: https://pkgs.tailscale.com/{{ release_stability | lower }}/centos/{{ ansible_distribution_major_version }}/tailscale.repo
  RedHat: https://pkgs.tailscale.com/{{ release_stability | lower }}/{{ "rhel" if ansible_distribution_major_version | int == 8 else "centos" }}/{{ ansible_distribution_major_version }}/tailscale.repo
  OracleLinux: https://pkgs.tailscale.com/{{ release_stability | lower }}/centos/{{ ansible_distribution_major_version }}/tailscale.repo
  Rocky: https://pkgs.tailscale.com/{{ release_stability | lower }}/centos/{{ ansible_distribution_major_version }}/tailscale.repo
  AlmaLinux: https://pkgs.tailscale.com/{{ release_stability | lower }}/centos/{{ ansible_distribution_major_version }}/tailscale.repo

dnf_dependencies:
  - python-dnf

dnf_yum_dependencies:
  - dnf-plugins-core

dnf_repos:
  Fedora: https://pkgs.tailscale.com/{{ release_stability | lower }}/fedora/tailscale.repo

original_distribution_major_version: "{{ ansible_distribution_major_version }}"

hosts: portainer
  tasks:
  - name: Debian | Apt Update
    become: true
    ansible.builtin.apt:
      update_cache: true

  - name: Debian | Apt Dependencies
    become: true
    ansible.builtin.apt:
      name: "{{ apt_dependencies }}"
      state: present

  - name: Debian | Legacy Apt Dependencies
    become: true
    ansible.builtin.apt:
      name: "{{ legacy_apt_dependencies }}"
    when:
      - ansible_distribution_major_version | int < 11
      - ansible_distribution_major_version != "testing"

  - name: Debian | Add Tailscale Signing Key
    become: true
    ansible.builtin.get_url:
      url: "{{ apt_signkey }}"
      dest: "{{ apt_keyring_path }}"
      mode: '0644'

  - name: Debian | Add Tailscale Deb
    become: true
    ansible.builtin.apt_repository:
      repo: "{{ apt_deb }}"
      state: present

  - name: Debian | Install Tailscale
    become: true
    ansible.builtin.apt:
      name: "{{ tailscale_package }}"
      state: '{{ state }}'
      update_cache: true